[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
chrono = "0.4.42"
chrono-tz = "0.10.4"
iana-time-zone = "0.1.63"
rmcp = "0.6.4"
serde = "1.0.219"
serde_json = "1.0.143"
thiserror = "2.0.16"
tokio = "1.47.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

mcp_server_time = { path = "crates/time_mcp" }
